name: philippines_rpcmb
description: A Flutter widgets that show List of Philippine Regions, Provinces, Cities, Municipalities, and Barangays
version: 0.0.2
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

assets:
  - assets/
